[package]
name = "castep-cell-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
castep-periodic-table = "0.3.2"
serde = { version = "1.0.198", features = ["derive"] }
winnow = "0.6"
