[package]
name = "castep-param-derive"
description = "Proc macro derives for `castep-param-io`"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version = "2.0.95", features = ["full"] }

[lib]
proc_macro = true
